%% Reformat the authoritative aggressive.m output for one IEEE column.
%
% This script deliberately leaves all signal processing to aggressive.m.
% It only presents the resulting time, signals, and filtered variables as
% four vertically aligned axes so the trajectories remain legible.

run('C:\Github\Tesis\docs\Propuesta Urucom\scripts\agressive.m');

panelOutputFile = ...
    'C:\Github\Tesis\docs\Urucom_2026_compact\imagenes\autocalibration_stage_outputs_agressive.png';

panelFig = figure( ...
    'Color', 'w', ...
    'Position', [100 100 900 1050]);

panelLayout = tiledlayout( ...
    panelFig, ...
    4, ...
    1, ...
    'TileSpacing', 'compact', ...
    'Padding', 'compact');

for channel = 1:size(signals, 2)

    panelAx = nexttile(panelLayout);
    hold(panelAx, 'on');

    plot( ...
        panelAx, ...
        time, ...
        signals(:, channel), ...
        '--', ...
        'Color', [0.68 0.68 0.68], ...
        'LineWidth', 1.35);

    plot( ...
        panelAx, ...
        time, ...
        filtered(:, channel), ...
        '-', ...
        'Color', colors(channel, :), ...
        'LineWidth', 2.40);

    channelLimits = [signals(:, channel); filtered(:, channel)];
    channelLimits = channelLimits(isfinite(channelLimits));
    yMinimum = min(channelLimits);
    yMaximum = max(channelLimits);
    yPadding = max(0.05 * (yMaximum - yMinimum), 0.015);

    xlim(panelAx, [displayStart displayEnd]);
    ylim(panelAx, [yMinimum - yPadding, yMaximum + yPadding]);
    ylabel(panelAx, sprintf('%s (V)', labels{channel}));
    grid(panelAx, 'on');
    box(panelAx, 'on');

    set( ...
        panelAx, ...
        'FontName', 'Times New Roman', ...
        'FontSize', 22, ...
        'LineWidth', 1.2, ...
        'GridAlpha', 0.16, ...
        'MinorGridAlpha', 0.08);

    if channel < size(signals, 2)
        panelAx.XTickLabel = [];
    else
        xlabel(panelAx, 'Time (s)');
    end

end


exportgraphics( ...
    panelFig, ...
    panelOutputFile, ...
    'Resolution', 300);

fprintf('Saved single-column figure from aggressive.m data:\n%s\n', ...
    panelOutputFile);
